#include "g53_port_pas.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Differential fixture is generated by the pinned, independently validated
 * Oracle with the contract's M820 96-transition geometry. */
int main(void)
{
    const char *path = "integration/evidence/evd-tq/TQ-06/host/pas/pas-reference.csv";
    FILE *file = fopen(path, "r");
    if (!file) { perror(path); return 1; }
    char line[1024];
    if (!fgets(line, sizeof(line), file)) return 1;
    g53_pas_ctx_t ctx;
    memset(&ctx, 0xa5, sizeof(ctx));
    unsigned rows = 0;
    while (fgets(line, sizeof(line), file)) {
        long expected[29];
        char *cursor = line;
        for (unsigned i = 0; i < 29; ++i) {
            char *end;
            expected[i] = strtol(cursor, &end, 10);
            if (end == cursor || (i < 28 && *end != ',')) {
                fprintf(stderr, "Malformed fixture row %u field %u\n", rows + 1, i);
                return 1;
            }
            cursor = end + 1;
        }
        if (expected[0]) g53_pas_reset(&ctx, expected[1] != 0, (uint8_t)expected[2]);
        g53_pas_output_t out = g53_pas_step(&ctx, (uint8_t)expected[2], (uint8_t)expected[3]);
        const int32_t actual[] = {
            out.direction,
            out.direction_candidate,
            out.cadence,
            out.evidence,
            out.movement,
            out.base_timeout_ticks,
            out.full_timeout_ticks,
            out.max_timeout_ticks,
            out.no_transition_ticks,
            out.code,
            out.anti_rock,
            out.span,
            out.magnitude,
            out.raw_cadence,
            out.current_delta,
            out.previous_delta,
            out.transition_count,
            out.elapsed_ticks,
            out.filter_accumulator,
            out.filtered_cadence,
            out.plausibility_budget,
            out.plausibility_base,
            out.plausibility_latch,
            out.plausibility_previous_latch,
            out.plausibility_flag
        };
        const char *names[] = {"direction", "direction_candidate", "cadence", "evidence", "movement", "base_timeout_ticks", "full_timeout_ticks", "max_timeout_ticks", "no_transition_ticks", "code", "anti_rock", "span", "magnitude", "raw_cadence", "current_delta", "previous_delta", "transition_count", "elapsed_ticks", "filter_accumulator", "filtered_cadence", "plausibility_budget", "plausibility_base", "plausibility_latch", "plausibility_previous_latch", "plausibility_flag"};
        for (unsigned i = 0; i < 25; ++i) {
            if (actual[i] != expected[i + 4]) {
                fprintf(stderr, "PAS row %u %s: actual=%ld expected=%ld\n",
                    rows + 1, names[i], (long)actual[i], expected[i + 4]);
                return 1;
            }
        }
        ++rows;
    }
    if (ferror(file) || rows != 28341) return 1;
    fclose(file);
    printf("G53 PAS: %u rows x 25 fields, zero mismatches PASS\n", rows);
    return 0;
}
