#!/usr/bin/env python3
"""Assist Behavior V3 scenario matrix: BASELINE vs CANDIDATE on identical rider scripts.

BASELINE  = production src/ + inc/ exported from the frozen baseline commit (default 25df554,
            docs/assist-v3/BASELINE_FREEZE.md) compiled with the CURRENT harness
            (sim/evist_sil.c + tests/host/common/rider_script.c + host stubs).
CANDIDATE = the current tree, same harness, same flags (plus --candidate-cflags, e.g.
            -DASSIST_V3 once the V3 module exists).

Both are built from the module list in tools/run_sil.py (production files missing from the
baseline export are dropped for the baseline only). Scenarios are expanded from
sim/v3_scenarios/matrix_spec.json into rider_script files; every scenario runs on both
binaries; tools/assist_v3_metrics.py scores both traces.

Outputs (all under .build/assist_v3/, gitignored):
  scenarios/*.txt            generated scripts
  {baseline,candidate}/*.csv per-tick traces
  out/matrix.csv             scenario x metric: baseline, candidate, delta, verdicts
  out/summary.md             markdown tables (per profile x cadence, cadence invariance)

--equivalence (G-EQ): additionally asserts byte-identical traces for every scenario, and
byte-identical fixed-mode SIL CSVs + stdout and fuzz stdout between the two builds. Exit 1 on
any difference.
"""
from __future__ import annotations

import argparse
import concurrent.futures as cf
import csv
import io
import json
import math
import os
import shutil
import subprocess
import sys
import tarfile
import time
from pathlib import Path

R = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(R / 'tools'))
import assist_v3_metrics as M  # noqa: E402
import run_sil  # noqa: E402  (module list only; main() is guarded)

EXE = '.exe' if os.name == 'nt' else ''
BUILD = R / '.build' / 'assist_v3'
SPEC = R / 'sim' / 'v3_scenarios' / 'matrix_spec.json'
HARNESS = ['sim/evist_sil.c', 'sim/l4/eb74_invocation_observer.c']
FLAGS = ['-std=c11', '-Wall', '-Wextra', '-Werror', '-Wno-type-limits', '-O2']

# Metrics shown in the markdown summary, per profile (all metrics go to matrix.csv).
SUMMARY_METRICS = {
    'steady': ['ripple_rev_median', 'phase_dip_fp_rate', 'energy_iq_s'],
    'dead_spot': ['ripple_rev_median', 'phase_dip_fp_rate', 'phase_dip_worst_drop'],
    'asymmetry': ['ripple_rev_median', 'phase_dip_fp_rate'],
    'climb': ['ripple_rev_median', 'phase_dip_fp_rate'],
    'pas_glitch': ['ripple_rev_max', 'phase_dip_fp_rate'],
    'stall_noise': ['ripple_rev_max', 'phase_dip_fp_rate'],
    'true_release': ['release_latency_50_ms', 'release_latency_50_deg', 'release_latency_10_ms'],
    'gradual_release': ['lower_demand_ms', 'lower_demand_deg', 'lower_demand_lag_ms'],
    'crest': ['lower_demand_ms', 'lower_demand_lag_ms'],
    'attack': ['attack_t63_ms', 'attack_t63_deg'],
    'attack_stop': ['attack_t63_ms', 'safety_ref0_ms', 'safety_drive0_ms'],
    'attack_stop_restart': ['restart_first_iq_ms', 'restart_t50_ms', 'restart_dip_frac'],
    'coast': ['safety_ref0_ms'],
    'reverse': ['safety_ref0_ms', 'safety_overshoot'],
    'brake': ['safety_ref0_ms', 'safety_drive0_ms'],
}
INVARIANCE_METRICS = ['release_latency_50_deg', 'release_latency_50_ms', 'phase_dip_fp_rate',
                      'ripple_rev_median', 'attack_t63_ms', 'lower_demand_lag_ms']


# ------------------------------------------------------------------------------- scenarios

def _fmt(x: float) -> str:
    s = f'{x:.6f}'.rstrip('0').rstrip('.')
    return s if s not in ('', '-0') else '0'


def _rng(v, scale=1.0) -> str:
    if isinstance(v, list):
        return f'{_fmt(v[0] * scale)}:{_fmt(v[1] * scale)}'
    return _fmt(v * scale)


def render_script(spec: dict, profile: str, cadence: float) -> tuple[str, str]:
    base = spec['base']
    p = spec['profiles'][profile]
    name = f'{profile}_{int(cadence)}'
    shape = dict(base['shape'])
    shape.update(p.get('shape', {}))
    mean = float(base['mean_ckg'])
    rv = base['reverse_rpm']
    rev_rpm = -max(rv['min'], min(rv['max'], cadence * rv['fraction']))
    lines = [
        '# generated by tools/run_assist_v3_matrix.py from sim/v3_scenarios/matrix_spec.json',
        f'name {name}',
        f'seed {base["seed"]}',
        f'noise {_fmt(mean * p.get("noise_fraction", 0.0))}',
        f'cadence_ripple {_fmt(p.get("cadence_ripple", base["cadence_ripple"]))}',
        'shape ' + ' '.join(f'{k}={_fmt(shape[k])}' for k in
                            ('ripple', 'asym', 'dsdepth', 'dswidth', 'phase')),
        f'start_angle {_fmt(base["start_angle"])}',
        f'level {base["level"]}',
        f'legal {base["legal"]}',
        f'decimate {base["decimate"]}',
    ]
    first = True
    for s in p['segments']:
        dur = s['dur']
        if isinstance(dur, dict):   # {"s": seconds, "revs": n} -> at least n revolutions
            dur = max(dur['s'], dur.get('revs', 0) * 60.0 / cadence)
        toks = [f'seg {s["kind"]}', f'dur={_fmt(dur)}']
        if 'rpm' in s:
            r = s['rpm']
            toks.append('rpm=' + (_fmt(cadence) if r == 'c' else _fmt(rev_rpm) if r == 'rev'
                                  else _rng(r)))
        if 'mean' in s:
            toks.append('mean=' + _rng(s['mean'], mean))
        if 'speed' in s:
            toks.append('speed=' + _rng(s['speed']))
        elif first:
            toks.append(f'speed={_fmt(base["speed_kmh"])}')
        first = False
        lines.append(' '.join(toks))
    for e in p.get('events', []):
        toks = [f'event {e["type"]}'] + [f'{k}={_fmt(v)}' for k, v in e.items() if k != 'type']
        lines.append(' '.join(toks))
    return name, '\n'.join(lines) + '\n'


def generate(spec: dict, cadences, profiles, outdir: Path) -> list[dict]:
    outdir.mkdir(parents=True, exist_ok=True)
    out = []
    for prof in profiles:
        for c in cadences:
            name, text = render_script(spec, prof, c)
            path = outdir / f'{name}.txt'
            path.write_bytes(text.encode())
            out.append({'name': name, 'profile': prof, 'cadence': c, 'script': path})
    return out


# ------------------------------------------------------------------------------- builds

def export_baseline(ref: str, dest: Path) -> None:
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)
    blob = subprocess.run(['git', 'archive', '--format=tar', ref, 'src', 'inc'], cwd=R,
                          check=True, stdout=subprocess.PIPE).stdout
    with tarfile.open(fileobj=io.BytesIO(blob)) as tf:
        tf.extractall(dest, filter='data')
    (dest / 'REF.txt').write_text(subprocess.run(
        ['git', 'rev-parse', ref], cwd=R, check=True, text=True,
        stdout=subprocess.PIPE).stdout)


def build(exe: Path, src_root: Path, extra_flags=()) -> float:
    prod = [m for m in run_sil.mods if m.startswith('src/')]
    other = [m for m in run_sil.mods if not m.startswith('src/')]
    srcs = [str(src_root / m) for m in prod if (src_root / m).exists()]
    if src_root == R:
        srcs = prod
    cc = os.environ.get('CC', 'gcc')
    inc = str(src_root / 'inc') if src_root != R else 'inc'
    cmd = [cc, *FLAGS, *extra_flags, '-Isim/l4', '-I' + inc, '-Itests/host/common/host_stubs',
           '-Itests/host/common', '-o', str(exe), *HARNESS, *srcs, *other,
           '-Wl,--wrap=g53_ad7ec_step', '-lm']
    exe.parent.mkdir(parents=True, exist_ok=True)
    t0 = time.perf_counter()
    p = subprocess.run(cmd, cwd=R, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if p.returncode:
        print(p.stdout)
        raise SystemExit(f'build failed: {exe}')
    return time.perf_counter() - t0


# ------------------------------------------------------------------------------- runs

def run_batch(exe: Path, items: list[dict], outdir: Path) -> str:
    args = [str(exe), '--script']
    for it in items:
        args += [str(it['script']), str(outdir / f'{it["name"]}.csv')]
    p = subprocess.run(args, cwd=R, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if p.returncode:
        raise SystemExit(f'{exe.name} --script failed:\n{p.stdout}')
    return p.stdout


def run_variant(exe: Path, scenarios: list[dict], outdir: Path, jobs: int) -> str:
    """One process per scenario. Several scripts in one process are NOT independent: some
    production chain state survives sim_init()/ride_control_init() (found 2026-10-07: coast_80
    alone vs after reverse_60 diverges at t=4.02 s, m2aa 0 vs 3162), so each scenario starts
    from a cold process = power-on state, independent of matrix order and subset."""
    outdir.mkdir(parents=True, exist_ok=True)
    batches = [[s] for s in scenarios]
    with cf.ThreadPoolExecutor(jobs) as ex:
        return ''.join(ex.map(lambda b: run_batch(exe, b, outdir), batches))


def _score(args):
    path, profile = args
    return M.scenario_metrics(M.load_trace(path), profile)


# ------------------------------------------------------------------------------- equivalence

def fixed_mode_equivalence(exes: dict[str, Path]) -> list[str]:
    """Existing SIL modes (fixed scenarios + stop/restart/axis + fuzz) on both builds."""
    problems = []
    outs = {}
    for tag, exe in exes.items():
        wd = BUILD / 'eq_fixed' / tag
        if wd.exists():
            shutil.rmtree(wd)
        (wd / '.build' / 'sil').mkdir(parents=True)
        p = subprocess.run([str(exe)], cwd=wd, text=True, stdout=subprocess.PIPE,
                           stderr=subprocess.STDOUT)
        f = subprocess.run([str(exe), '--fuzz', '100', '0xE7157A39'], cwd=wd, text=True,
                           stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        if p.returncode or f.returncode:
            problems.append(f'{tag}: fixed/fuzz run failed rc={p.returncode}/{f.returncode}')
        outs[tag] = (p.stdout, f.stdout, wd / '.build' / 'sil')
    (bs, bf, bd), (cs, cfz, cd) = outs['baseline'], outs['candidate']
    if bs != cs:
        problems.append('fixed-mode stdout differs')
    if bf != cfz:
        problems.append('fuzz stdout differs')
    names = sorted(x.name for x in bd.glob('*.csv'))
    if names != sorted(x.name for x in cd.glob('*.csv')) or not names:
        problems.append('fixed-mode CSV sets differ or are empty')
    for n in names:
        if (bd / n).read_bytes() != (cd / n).read_bytes():
            problems.append(f'fixed-mode CSV differs: {n}')
    return problems, len(names)


# ------------------------------------------------------------------------------- report

def _num(v):
    return v if isinstance(v, (int, float)) and not isinstance(v, bool) else None


def _show(v) -> str:
    if v is None:
        return '-'
    if isinstance(v, str):
        return 'REFUSED' if v.startswith('REFUSED') else v
    if isinstance(v, float) and math.isinf(v):
        return 'never'
    if isinstance(v, float):
        return f'{v:.3f}' if abs(v) < 10 else f'{v:.1f}'
    return str(v)


def write_reports(scenarios, scores, outdir: Path, meta: dict) -> None:
    outdir.mkdir(parents=True, exist_ok=True)
    rows = []
    for sc in scenarios:
        b, c = scores['baseline'][sc['name']], scores['candidate'][sc['name']]
        for k in sorted(set(b) | set(c)):
            bv, cv = b.get(k), c.get(k)
            bn, cn = _num(bv), _num(cv)
            delta = (cn - bn) if (bn is not None and cn is not None and
                                  math.isfinite(bn) and math.isfinite(cn)) else ''
            chk = lambda v: ('' if k not in M.CHECKS else
                             ('PASS' if M.check(k, _num(v)) else 'FAIL'))
            rows.append([sc['name'], sc['profile'], sc['cadence'], k, bv, cv, delta,
                         chk(bv), chk(cv)])
    inv_rows = []
    for prof in sorted({s['profile'] for s in scenarios}):
        for k in INVARIANCE_METRICS:
            for tag in ('baseline', 'candidate'):
                vals = {s['cadence']: _num(scores[tag][s['name']].get(k))
                        for s in scenarios if s['profile'] == prof and k in scores[tag][s['name']]}
                if not vals:
                    continue
                try:
                    r = M.cadence_invariance(vals)
                    inv_rows.append([prof, k, tag, r['spread'], r['rel_spread'], r['points'],
                                     ' '.join(str(x) for x in r['missing'])])
                except M.MetricRefused as ex:
                    inv_rows.append([prof, k, tag, f'REFUSED: {ex}', '', len(vals), ''])
    with (outdir / 'matrix.csv').open('w', newline='') as f:
        w = csv.writer(f)
        w.writerow(['scenario', 'profile', 'cadence', 'metric', 'baseline', 'candidate', 'delta',
                    'baseline_check', 'candidate_check'])
        w.writerows(rows)
    with (outdir / 'cadence_invariance.csv').open('w', newline='') as f:
        w = csv.writer(f)
        w.writerow(['profile', 'metric', 'variant', 'spread', 'rel_spread', 'points',
                    'non_finite_cadences'])
        w.writerows(inv_rows)

    md = ['# Assist V3 scenario matrix', '',
          *(f'- {k}: {v}' for k, v in meta.items()), '',
          'Cell = baseline / candidate (delta). `never` = threshold not reached inside the '
          'segment; `REFUSED` = evidence unusable (see matrix.csv). Definitions: '
          'tools/assist_v3_metrics.py docstring.', '']
    for prof, keys in SUMMARY_METRICS.items():
        sub = [s for s in scenarios if s['profile'] == prof]
        if not sub:
            continue
        md += [f'## {prof}', '', '| cadence | ' + ' | '.join(keys) + ' |',
               '|---|' + '---|' * len(keys)]
        for s in sub:
            cells = []
            for k in keys:
                bv = scores['baseline'][s['name']].get(k)
                cv = scores['candidate'][s['name']].get(k)
                bn, cn = _num(bv), _num(cv)
                d = (f' ({cn - bn:+.3g})' if bn is not None and cn is not None and
                     math.isfinite(bn) and math.isfinite(cn) and cn != bn else '')
                cells.append(f'{_show(bv)} / {_show(cv)}{d}')
            md.append(f'| {s["cadence"]} | ' + ' | '.join(cells) + ' |')
        md.append('')
    md += ['## Cadence invariance (spread across cadences)', '',
           '| profile | metric | variant | spread | rel spread | points |', '|---|---|---|---|---|---|']
    for r in inv_rows:
        md.append(f'| {r[0]} | {r[1]} | {r[2]} | {_show(r[3])} | {_show(r[4])} | {r[5]} |')
    (outdir / 'summary.md').write_text('\n'.join(md) + '\n', encoding='utf-8')


# ------------------------------------------------------------------------------- main

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--quick', action='store_true', help='Gate-1 subset from the spec')
    ap.add_argument('--equivalence', action='store_true',
                    help='G-EQ: require byte-identical baseline/candidate outputs')
    ap.add_argument('--baseline-ref', default='25df554')
    ap.add_argument('--candidate-cflags', default='', help='extra CFLAGS for the candidate only')
    ap.add_argument('--profiles', default='', help='comma list (default: all / quick set)')
    ap.add_argument('--cadences', default='', help='comma list (default: all / quick set)')
    ap.add_argument('--jobs', type=int, default=max(1, min(8, os.cpu_count() or 1)))
    ap.add_argument('--out', default=str(BUILD / 'out'))
    a = ap.parse_args()

    t_start = time.perf_counter()
    spec = json.loads(SPEC.read_text())
    cad = spec['quick']['cadences'] if a.quick else spec['cadences']
    prof = spec['quick']['profiles'] if a.quick else list(spec['profiles'])
    if a.cadences:
        cad = [int(x) for x in a.cadences.split(',')]
    if a.profiles:
        prof = a.profiles.split(',')
    unknown = [p for p in prof if p not in spec['profiles']]
    if unknown:
        raise SystemExit(f'unknown profile(s): {unknown}')

    base_src = BUILD / 'baseline_src'
    export_baseline(a.baseline_ref, base_src)
    exes = {'baseline': BUILD / 'bin' / f'evist_sil_baseline{EXE}',
            'candidate': BUILD / 'bin' / f'evist_sil_candidate{EXE}'}
    with cf.ThreadPoolExecutor(2) as ex:
        fb = ex.submit(build, exes['baseline'], base_src)
        fc = ex.submit(build, exes['candidate'], R, a.candidate_cflags.split())
        tb, tc = fb.result(), fc.result()
    t_built = time.perf_counter()

    scen = generate(spec, cad, prof, BUILD / 'scenarios')
    logs = {}
    for tag in ('baseline', 'candidate'):
        d = BUILD / tag
        if d.exists():
            shutil.rmtree(d)
        logs[tag] = run_variant(exes[tag], scen, d, a.jobs)
        (BUILD / f'{tag}_run.log').write_text(logs[tag])
    t_ran = time.perf_counter()

    scores = {}
    with cf.ProcessPoolExecutor(a.jobs) as ex:
        for tag in ('baseline', 'candidate'):
            res = ex.map(_score, [(BUILD / tag / f'{s["name"]}.csv', s['profile']) for s in scen])
            scores[tag] = {s['name']: r for s, r in zip(scen, res)}
    t_scored = time.perf_counter()

    rc = 0
    eq_note = 'not requested'
    if a.equivalence:
        diffs = [s['name'] for s in scen
                 if (BUILD / 'baseline' / f'{s["name"]}.csv').read_bytes() !=
                 (BUILD / 'candidate' / f'{s["name"]}.csv').read_bytes()]
        fixed_problems, nfixed = fixed_mode_equivalence(exes)
        # Same binary, same scripts, second run: the run_regression.py determinism technique.
        rerun_dir = BUILD / 'candidate_rerun'
        if rerun_dir.exists():
            shutil.rmtree(rerun_dir)
        sample = scen[::max(1, len(scen) // 10)]
        run_variant(exes['candidate'], sample, rerun_dir, a.jobs)
        fixed_problems += [f'non-deterministic rerun: {s["name"]}' for s in sample
                           if (rerun_dir / f'{s["name"]}.csv').read_bytes() !=
                           (BUILD / 'candidate' / f'{s["name"]}.csv').read_bytes()]
        if diffs or fixed_problems:
            rc = 1
            eq_note = (f'FAIL: {len(diffs)} scenario trace(s) differ {diffs[:5]}; '
                       f'fixed-mode: {fixed_problems}')
        else:
            eq_note = (f'PASS: {len(scen)} scenario traces byte-identical; fixed-mode stdout + '
                       f'{nfixed} CSVs + fuzz(100) stdout byte-identical; '
                       f'{len(sample)} candidate reruns byte-identical')
        print('G-EQ', eq_note)

    meta = {
        'baseline': f'{a.baseline_ref} src/+inc/ (`{(base_src / "REF.txt").read_text().strip()}`)'
                    ' + current harness',
        'candidate': 'current tree' + (f' + {a.candidate_cflags}' if a.candidate_cflags else ''),
        'scenarios': f'{len(scen)} ({"quick" if a.quick else "full"}: cadences {cad})',
        'demand signal': 'iq_ref (published Iq after fast_iq_slew)',
        'G-EQ': eq_note,
        'timing': f'build {max(tb, tc):.1f}s (parallel), runs {t_ran - t_built:.1f}s, '
                  f'metrics {t_scored - t_ran:.1f}s, total {time.perf_counter() - t_start:.1f}s',
    }
    write_reports(scen, scores, Path(a.out), meta)
    print(f'scenarios={len(scen)} build={max(tb, tc):.1f}s runs={t_ran - t_built:.1f}s '
          f'metrics={t_scored - t_ran:.1f}s total={time.perf_counter() - t_start:.1f}s')
    print(Path(a.out) / 'matrix.csv')
    print(Path(a.out) / 'summary.md')
    return rc


if __name__ == '__main__':
    raise SystemExit(main())
