/*
 * CAN_Display.c
 *
 *  Created on: 19.10.2025
 *  Author: stancecoke
	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


#include "main.h"
#include "CAN_Display.h"
#include "parser.h"
#include "FOC.h"
#include "assist_modes.h"
#include "tuning_config.h"
#include "torque_input.h"
#include "ride_control.h"

/* Build version string for the HMI info field (0x6001). Generated by build_firmware.ps1
   into inc/build_version.h (gitignored, never committed). Falls back to "dev" for IDE builds. */
#if defined(__has_include)
#  if __has_include("build_version.h")
#    include "build_version.h"
#  endif
#endif
#ifndef EBICS_BUILD_VERSION
#define EBICS_BUILD_VERSION "dev"
#endif

Ext_ID_t Ext_ID_Rx;
Ext_ID_t Ext_ID_Tx;
void processCAN_Rx(MotorParams_t* MP, MotorState_t* MS);
void sendCAN_Tx(MotorParams_t* MP, MotorState_t* MS);
void sendCAN_Poll(MotorParams_t* MP, MotorState_t* MS, uint16_t command);
void sendAcknoledge(void);
void sendMultiframeWriteAck(uint16_t command);
void send_multiframe(uint16_t command, char* data, uint8_t length );
void append_multiframe(uint16_t command, char* data);
void update_checksum(void);
//int16_t abs(int16_t value);
char tx_data[64];
uint8_t Para0[64];
uint8_t Para1[64];
uint8_t Para2[64];
uint8_t BankBlob[192]; //FW-006: one serialized profile bank (185 B used, 8B-frame aligned)
uint8_t TuningBlob[16]; //FW-010: global ride-feel tuning blob
uint8_t TorqueBlob[24]; //FW-013: torque load telemetry + calibration status
extern volatile uint8_t bank_save_request; //FW-006/FW-010: set by 0x6022, consumed in main.c at standstill
extern volatile uint8_t ride_engine_request; //FW-014: set by 0x6027, applied in main.c at standstill
extern volatile uint8_t diag_peak_reset, diag_peak_cadence; //FW-015b: peak-hold diagnostics
extern volatile uint16_t diag_peak_torque, diag_peak_human_w, diag_peak_support, diag_peak_motor_w;
extern volatile int32_t diag_peak_iq_req, diag_peak_iq_set;
uint8_t tx_data_length;
uint8_t rx_data_length;
uint8_t nbrofframes;
float last_distance =0;
float last_kilometer =0;
float distance =0;
uint16_t display_distance=0;
uint16_t delay_counter =0;
uint16_t k=0;
uint8_t level_code;
uint8_t level_code_old;
uint8_t level_counter;
extern volatile uint16_t comm_lost_ticks; //comms watchdog counter (defined in main.c) - reset on each HMI frame
extern volatile uint8_t comm_seen;        //comms watchdog arm flag (defined in main.c) - set on first HMI frame
extern uint8_t auto_off_minutes;          //runtime auto-off timeout [min] (defined in main.c) - set from HMI 0x6303
uint8_t walk_can_code_old;
uint8_t walk_can_counter;

uint16_t Rx_MF_active=0;
uint16_t checksum=0;

void processCAN_Rx(MotorParams_t* MP, MotorState_t* MS){

	Ext_ID_Rx.command = (receive_message.rx_efid)&0xFFFF;
	Ext_ID_Rx.operation = (receive_message.rx_efid>>16)&0x07; //only 3 bit width
	Ext_ID_Rx.target = (receive_message.rx_efid>>19)&0x1F; //only 5 bit width
	Ext_ID_Rx.source = (receive_message.rx_efid>>24)&0x1F;

	if(Ext_ID_Rx.target==2){ //controller answers on target=2 only (factory ignores tgt=4 info queries; answering duplicates pollutes target=3)
		comm_lost_ticks=0; //comms watchdog: HMI is alive, reset loss counter
		comm_seen=1;       //arm the watchdog after the first HMI frame (boot grace period ends here)
		switch (Ext_ID_Rx.operation){
			case WRITE_CMD:

				if (receive_message.rx_dlen==1 && receive_message.rx_data[0]>8 && Ext_ID_Rx.source==5){
					Rx_MF_active=Ext_ID_Rx.command;
					rx_data_length=receive_message.rx_data[0];
				}
				else if(Ext_ID_Rx.command==0x6022 && Ext_ID_Rx.source==5){ //FW-006: persist banks (deferred to standstill)
					bank_save_request=1;
				}
				else if(Ext_ID_Rx.command==0x6026 && Ext_ID_Rx.source==5){ //FW-013: torque load calibration operations
					switch(receive_message.rx_data[0]){
						case 1: torque_input_cal_start(); break;
						case 2: torque_input_cal_capture_load(receive_message.rx_data[1]+(receive_message.rx_data[2]<<8)); break;
						case 3: torque_input_cal_commit(); break;
						case 4: torque_input_cal_cancel(); break;
						case 5: torque_input_cal_restore_default(); break;
					}
				}
				else if(Ext_ID_Rx.command==0x6027 && Ext_ID_Rx.source==5){ //FW-014: request ride engine switch (applied at standstill)
					ride_engine_request = receive_message.rx_data[0] ? 1 : 0;
				}
				else if(Ext_ID_Rx.command==0x62D9){ //Startup angle, used as multiplyer here
					MP->TS_coeff=receive_message.rx_data[0]+(receive_message.rx_data[1]<<8);
					//save received setting
					write_virtual_eeprom();
				}

				else sendCAN_Tx(MP,MS);
				//Factory sends NO WRITE-ACK for the continuous operational data 0x6300-0x6304; only for
				//config writes. ACKing 0x630x floods 0x822A630x that the factory never emits -> exact-match test.
				if(!(Ext_ID_Rx.command>=0x6300 && Ext_ID_Rx.command<=0x6304)) sendAcknoledge();
				break;
			case READ_CMD:
				sendCAN_Tx(MP,MS);
				break;
			case LONG_START_CMD:
				switch (Rx_MF_active){
					case 0x6010: //Para0
						append_multiframe(0, &Para0[0]);
						break;
					case 0x6011: //Para1
						append_multiframe(0, &Para1[0]);
						break;
					case 0x6012: //Para2
						append_multiframe(0, &Para2[0]);
						break;
					case 0x6021: //FW-006: bank write
						append_multiframe(0, (char*)&BankBlob[0]);
						break;
					case 0x6024: //FW-010: tuning write
						append_multiframe(0, (char*)&TuningBlob[0]);
						break;
				}

				break;
			case LONG_TRANG_CMD:
				switch (Rx_MF_active){
					case 0x6010: //Para0
						append_multiframe(Ext_ID_Rx.command+1, &Para0[0]);
						break;
					case 0x6011: //Para1
						append_multiframe(Ext_ID_Rx.command+1, &Para1[0]);
						break;
					case 0x6012: //Para2
						append_multiframe(Ext_ID_Rx.command+1, &Para2[0]);
						break;
					case 0x6021: //FW-006: bank write (frame index bounded by rx_data_length<=192)
						if(Ext_ID_Rx.command < 23) append_multiframe(Ext_ID_Rx.command+1, (char*)&BankBlob[0]);
						break;
					case 0x6024: //FW-010: tuning write (frame index bounded by rx_data_length<=16)
						if(Ext_ID_Rx.command < 2) append_multiframe(Ext_ID_Rx.command+1, (char*)&TuningBlob[0]);
						break;
				}
				break;

			case LONG_END_CMD:
				switch (Rx_MF_active){
					case 0x6010: //Para0
						append_multiframe(Ext_ID_Rx.command+1, &Para0[0]);
						break;
					case 0x6011: //Para1
						append_multiframe(Ext_ID_Rx.command+1, &Para1[0]);

						break;
					case 0x6012: //Para2
						append_multiframe(Ext_ID_Rx.command+1, &Para2[0]);

						break;
					case 0x6021: //FW-006: bank write
						if(Ext_ID_Rx.command < 23) append_multiframe(Ext_ID_Rx.command+1, (char*)&BankBlob[0]);
						break;
					case 0x6024: //FW-010: tuning write
						if(Ext_ID_Rx.command < 2) append_multiframe(Ext_ID_Rx.command+1, (char*)&TuningBlob[0]);
						break;
				}
				k = ((Ext_ID_Rx.command+1)<<3)+receive_message.rx_dlen;
				if(((Ext_ID_Rx.command+1)<<3)+receive_message.rx_dlen==rx_data_length){
					//to do send acknoledge OK
					uint16_t completed_cmd = Rx_MF_active;
					Rx_MF_active=0;
					//save received setting
					if(completed_cmd==0x6021){
						//FW-006: RAM apply only; flash write happens via 0x6022 at standstill
						assist_modes_apply_bank_blob(&BankBlob[0], rx_data_length);
						sendMultiframeWriteAck(completed_cmd); //final ACK so the tool doesn't time out
					}
					else if(completed_cmd==0x6024){
						//FW-010: RAM apply only; flash write happens via 0x6022 at standstill
						tuning_config_apply_blob(&TuningBlob[0], rx_data_length);
						sendMultiframeWriteAck(completed_cmd);
					}
					else{
						parse_DPparams(MP);
						write_virtual_eeprom();
					}
					rx_data_length=0;

				}
				else{
					//to do send acknoledge NOK
					Rx_MF_active=0;
					rx_data_length=0;
				}

				break;
		}


		if(Ext_ID_Rx.command==0x6300){
			level_code=receive_message.rx_data[1];
			if(level_code==level_code_old&&level_counter<3)level_counter++;
			if(level_code!=level_code_old){

				level_counter=0;
				}
			level_code_old=level_code;

			if(level_counter==3){

				level_counter=4;
				switch (level_code){
					case 0:
						MS->assist_level=0;
						break;
					case 1:
						MS->assist_level=1;
						break;
					case 0x0B:
						MS->assist_level=2; //Eco
						break;
					case 0x0C:
						MS->assist_level=3;
						break;
					case 0x0D:
						MS->assist_level=4; //Tour
						break;
					case 0x02:
						MS->assist_level=5;
						break;
					case 0x15:
						MS->assist_level=6;//Sport
						break;
					case 0x16:
						MS->assist_level=7;
						break;
					case 0x17:
						MS->assist_level=8; //Sport +
						break;
					case 0x03:
						MS->assist_level=9; //Boost
						break;
				}
			}
			// Walk Assist request from display: only sets walk_can_request (with debounce).
			// pushassist_flag itself is derived in main.c (requires physical PA4 button held).
			if (receive_message.rx_data[1]==6){
				if(receive_message.rx_data[1]==walk_can_code_old){
					if(walk_can_counter<3)walk_can_counter++;
				}else{
					walk_can_counter=0;
				}
				if(walk_can_counter>=3)MS->walk_can_request=SET;
			}else{
				walk_can_counter=0;
				MS->walk_can_request=RESET;
			}
			walk_can_code_old=receive_message.rx_data[1];
			if (receive_message.rx_data[2]&0b1)MS->light_flag=SET;
			else MS->light_flag=RESET;
			if (receive_message.rx_data[2]&0b10)MS->button_up_flag=SET;
			else MS->button_up_flag=RESET;
			if (receive_message.rx_data[2]&0b100000)MS->button_down_flag=SET;
			else MS->button_down_flag=RESET;

		}

		if(Ext_ID_Rx.command==0x6303 && receive_message.rx_dlen>=1){ //auto-off timeout [min] set on the HMI
			auto_off_minutes=receive_message.rx_data[0]; //overwrites the AUTO_OFF_MINUTES default
		}

		if(Ext_ID_Rx.command==0x3203&&Ext_ID_Rx.operation==WRITE_CMD){ //speed limit and wheel size
			MP->speedLimitx100=receive_message.rx_data[0]+(receive_message.rx_data[1]<<8);
			MP->wheel_cirumference=receive_message.rx_data[4]+(receive_message.rx_data[5]<<8);
			//save received setting
			write_virtual_eeprom();

		}

		if(Ext_ID_Rx.command==0x6200){ //Position sensor calibration
			autodetect();
		}
		if(Ext_ID_Rx.command==0x6101){ //Torque sensor calibration normally, here used for factory settings reset
			InitEEPROM(MP);
			read_virtual_eeprom();
			parse_MOparams(MP);

		}



	}
	// NOTE: 0x6400/0x6401 (single-frame 0x8228 version/model) handlers REMOVED for exact factory match —
	// the factory M820 does NOT answer these and the HMI shows info without them. See git history if needed.
	if(Ext_ID_Rx.command==0x3005){ //jump to bootloader for firmware update
		NVIC_SystemReset();
	}
}
//FW-006/FW-010: explicit write-ACK for a completed multiframe block. At LONG_END the
//received command id is the last frame index, so the acknowledged command must be passed in.
void sendMultiframeWriteAck(uint16_t command){
	Ext_ID_Tx.command = command;
	Ext_ID_Tx.operation = 2; //acknoledge OK
	Ext_ID_Tx.target = Ext_ID_Rx.source; //reply to the requester (Canable/BESST = 5)
	Ext_ID_Tx.source = 0x02;
	transmit_message.tx_sfid = 0x00;
	transmit_message.tx_efid = Ext_ID_Tx.command+(Ext_ID_Tx.operation<<16)+(Ext_ID_Tx.target<<19)+(Ext_ID_Tx.source<<24);
	transmit_message.tx_ft = CAN_FT_DATA;
	transmit_message.tx_ff = CAN_FF_EXTENDED;
	transmit_message.tx_dlen = 0;
	transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
	timeout = 0xFFFF;
	while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)) timeout--;
}

void sendAcknoledge(void){
	Ext_ID_Tx.command = Ext_ID_Rx.command;
	Ext_ID_Tx.operation = 2; //acknoledge OK
	Ext_ID_Tx.target = 5; //WRITE-ACK ALWAYS to target=5 (HMI write-ACK port). Replying to source(=3) pollutes
	                      //the target=3 READ channel with ACKs and breaks the info multiframe -> blank HMI info.
	Ext_ID_Tx.source = 0x02; //controller
	transmit_message.tx_sfid = 0x00;
	transmit_message.tx_efid = Ext_ID_Tx.command+(Ext_ID_Tx.operation<<16)+(Ext_ID_Tx.target<<19)+(Ext_ID_Tx.source<<24);
	transmit_message.tx_ft = CAN_FT_DATA;
	transmit_message.tx_ff = CAN_FF_EXTENDED;
	transmit_message.tx_dlen = 0;

	/* transmit message */
	transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
	/* waiting for transmit completed */
	timeout = 0xFFFF;
	while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
		timeout--;
		}

}

void sendCAN_3100(MotorState_t* MS){
	//Emulates the separate torque-sensor CAN node (source=01) that the original Bafang system has.
	//HMI reads real-time cadence and torque from this frame every 10ms.
	static uint8_t ctr = 0;
	transmit_message.tx_sfid    = 0x00;
	transmit_message.tx_efid    = 0x01F83100; //source=1 (torque sensor), target=31 broadcast
	transmit_message.tx_ft      = CAN_FT_DATA;
	transmit_message.tx_ff      = CAN_FF_EXTENDED;
	transmit_message.tx_dlen    = 4;
	transmit_message.tx_data[0] = (uint8_t)((uint16_t)MS->torque_on_crank & 0xFF);
	transmit_message.tx_data[1] = (uint8_t)((uint16_t)MS->torque_on_crank >> 8);
	transmit_message.tx_data[2] = MS->cadence;
	transmit_message.tx_data[3] = ctr++;
	transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
	timeout = 0xFFFF;
	while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
		timeout--;
	}
}

void sendCAN_3202(void){
	//Original firmware sends 0x3202 (1 byte 0x00) every ~100ms. HMI may lose sync or exit WA without it.
	uint32_t timeout;
	transmit_message.tx_sfid    = 0x00;
	transmit_message.tx_efid    = 0x02F83202;
	transmit_message.tx_ft      = CAN_FT_DATA;
	transmit_message.tx_ff      = CAN_FF_EXTENDED;
	transmit_message.tx_dlen    = 1;
	transmit_message.tx_data[0] = 0x00;
	transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
	timeout = 0xFFFF;
	while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
		timeout--;
	}
}

void sendCAN_Poll(MotorParams_t* MP, MotorState_t* MS, uint16_t command){

	switch (command){

		case 0x3201: //speed and power
			/* initialize transmit message */
			transmit_message.tx_sfid = 0x00;
			transmit_message.tx_efid = 0x02F83201;
			transmit_message.tx_ft = CAN_FT_DATA;
			transmit_message.tx_ff = CAN_FF_EXTENDED;
			transmit_message.tx_dlen = 8;
			if(MS->offroadtics){
				transmit_message.tx_data[0] = (MS->offroadtics*100)&0xFF;
				transmit_message.tx_data[1] = ((MS->offroadtics*100)>>8)&0xFF;
			}
			else if(MS->bank_splash_kmh){ //FW-005: bank switch feedback (10 = Power, 20 = eMTB)
				transmit_message.tx_data[0] = (MS->bank_splash_kmh*100)&0xFF;
				transmit_message.tx_data[1] = ((MS->bank_splash_kmh*100)>>8)&0xFF;
			}
			else{
				transmit_message.tx_data[0] = (MS->Speedx100)&0xFF;
				transmit_message.tx_data[1] = ((MS->Speedx100)>>8)&0xFF;
			}
			transmit_message.tx_data[2] = (abs(MS->Battery_Current)/10)&0xFF;
			transmit_message.tx_data[3] = ((abs(MS->Battery_Current)/10)>>8)&0xFF;
			transmit_message.tx_data[4] = (MS->Voltage/10)&0xFF;
			transmit_message.tx_data[5] = ((MS->Voltage/10)>>8)&0xFF;
			transmit_message.tx_data[6] = MS->int_Temperature+40; //temp sterownika (M820: jeden czujnik); +40 = offset protokolu, parser PC odejmuje 40
			transmit_message.tx_data[7] = MS->int_Temperature+40; //ta sama temp sterownika jako "motor temp"; +40 = offset protokolu (NIE przeklamanie)

			/* transmit message */
			transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
			/* waiting for transmit completed */
			timeout = 0xFFFF;
			while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
				timeout--;
				}
			break;

		case 0x3200: //battery and distance
			/* initialize transmit message */
			if(delay_counter<10)delay_counter++;
			else{
				delay_counter=0;
				distance=(MS->distance_since_startup)-last_kilometer;
				if(MS->distance_since_startup!=last_distance)display_distance = distance/10;
				else{
					display_distance = 0;
					last_kilometer=MS->distance_since_startup;
				}
				if(distance>1000)last_kilometer=MS->distance_since_startup;
				last_distance=MS->distance_since_startup;
			}
			transmit_message.tx_sfid = 0x00;
			transmit_message.tx_efid = 0x02F83200;
			transmit_message.tx_ft = CAN_FT_DATA;
			transmit_message.tx_ff = CAN_FF_EXTENDED;
			transmit_message.tx_dlen = 8;
			transmit_message.tx_data[0] = MS->SOC;//battery percentage
			transmit_message.tx_data[1] = (uint8_t)display_distance; // in 10m
			transmit_message.tx_data[2] = 0x00;
			transmit_message.tx_data[3] = MS->cadence; //cadence
			transmit_message.tx_data[4] = MS->torque_on_crank&0xFF; //torque mV LSB
			transmit_message.tx_data[5] = (MS->torque_on_crank>>8)&0xFF; //torque mv MSB
			//protocol unit for remaining range is 0.01 km (display divides by 100) -> send km*100
			{
				uint16_t range_x100 = (MS->range < 650) ? (uint16_t)(MS->range*100) : 64999;
				transmit_message.tx_data[6] = range_x100&0xFF;//range LSB (0.01 km)
				transmit_message.tx_data[7] = (range_x100>>8)&0xFF;//range MSB
			}

			/* transmit message */
			transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
			/* waiting for transmit completed */
			timeout = 0xFFFF;
			while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
				timeout--;
				}

			break;

		case 0x3205: //to do
			/* initialize transmit message */
			transmit_message.tx_sfid = 0x00;
			transmit_message.tx_efid = 0x02F83205;
			transmit_message.tx_ft = CAN_FT_DATA;
			transmit_message.tx_ff = CAN_FF_EXTENDED;
			transmit_message.tx_dlen = 2;
			transmit_message.tx_data[0] = MS->calories&0xFF; //calories
			transmit_message.tx_data[1] = (MS->calories>>8)&0xFF;


			/* transmit message */
			transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
			/* waiting for transmit completed */
			timeout = 0xFFFF;
			while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
				timeout--;
				}
			break;


	}//end case
}

void sendCAN_status_broadcast(MotorState_t* MS){
	//Controller alive/status heartbeat broadcast to HMI (replicates factory M820 firmware).
	//Without these the HMI does not blink the Walk Assist icon and drops out of WA after a few seconds.
	//Frames (source=2 controller, target=31 broadcast): 0x1200 (warning/brake), 0x320F (status active), 0x3000.
	static const uint32_t hb_efid[3] = {0x02FF1200, 0x02F8320F, 0x02F83000};
	static const uint8_t  hb_dlen[3] = {1, 8, 4};
	for(uint8_t i=0;i<3;i++){
		transmit_message.tx_sfid = 0x00;
		transmit_message.tx_efid = hb_efid[i];
		transmit_message.tx_ft = CAN_FT_DATA;
		transmit_message.tx_ff = CAN_FF_EXTENDED;
		transmit_message.tx_dlen = hb_dlen[i];
		for(uint8_t j=0;j<8;j++) transmit_message.tx_data[j]=0;
		if(i==0) transmit_message.tx_data[0] = (MS->brake_active_flag==SET) ? 0x01 : 0x00; //bit0=brake
		else if(i==1) transmit_message.tx_data[0] = 0x01;
		else { transmit_message.tx_data[3] = 0x0B; } //0x3000: byte3=0x0B matches orig firmware
		transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
		timeout = 0xFFFF;
		while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
			timeout--;
		}
	}
}

void sendCAN_Tx(MotorParams_t* MP, MotorState_t* MS){

	switch (Ext_ID_Rx.command){


		// Controller info as MULTIFRAME (like factory firmware) so the HMI shows name/version.
		// Strings kept factory-identical except the customer/serial field (0x6001) -> EBICS + build version.
		case 0x6000: //manufacturer / hw id (factory: "CR X30P.250.FC 2.1")
			if(Ext_ID_Rx.operation==1){
				tx_data_length=sprintf(tx_data, "CR X30P.250.FC 2.1");
				send_multiframe(Ext_ID_Rx.command, &tx_data[0], tx_data_length);
			}
			break;

		case 0x6001: //serial/customer field -> EBICS + current build version (factory was "FAKE TAXI ...")
			if(Ext_ID_Rx.operation==1){
				tx_data_length=sprintf(tx_data, "EBICS %s", EBICS_BUILD_VERSION);
				while(tx_data_length<20) tx_data[tx_data_length++]=' '; //pad to factory serial length (20)
				send_multiframe(Ext_ID_Rx.command, &tx_data[0], tx_data_length);
			}
			break;

		case 0x6002: //model number shown on HMI (factory: "CR X30P.250.FC")
			if(Ext_ID_Rx.operation==1){
				tx_data_length=sprintf(tx_data, "CR X30P.250.FC");
				send_multiframe(Ext_ID_Rx.command, &tx_data[0], tx_data_length);
			}
			break;

		case 0x62D9: //startup angle used as multiplyer here
			/* initialize transmit message */

			Ext_ID_Tx.command = 0x62D9;
			Ext_ID_Tx.operation = 2; //NORMAL_ACK — factory sends 0x821A62D9 (op=NORMAL_ACK), NOT WRITE. HMI needs this for wheel data.
			Ext_ID_Tx.target = Ext_ID_Rx.source; //reply to the requester (display=3, BESST=5...)
			Ext_ID_Tx.source = 0x02; //controller
			transmit_message.tx_sfid = 0x00;
			transmit_message.tx_efid = Ext_ID_Tx.command+(Ext_ID_Tx.operation<<16)+(Ext_ID_Tx.target<<19)+(Ext_ID_Tx.source<<24);
			transmit_message.tx_ft = CAN_FT_DATA;
			transmit_message.tx_ff = CAN_FF_EXTENDED;
			transmit_message.tx_dlen = 2;
			transmit_message.tx_data[0] =  (MP->TS_coeff)&0xFF;
			transmit_message.tx_data[1] =  (MP->TS_coeff>>8)&0xFF;

			/* transmit message */
			transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
			/* waiting for transmit completed */
			timeout = 0xFFFF;
			while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
				timeout--;
				}
			break;

		case 0x3203: //to do
			/* initialize transmit message */

			Ext_ID_Tx.command = 0x3203;
			Ext_ID_Tx.operation = 0; //write
			Ext_ID_Tx.target = Ext_ID_Rx.source; //reply to the requester (display=3, BESST=5...) - was hardcoded 5
			Ext_ID_Tx.source = 0x02; //controller
			transmit_message.tx_sfid = 0x00;
			transmit_message.tx_efid = Ext_ID_Tx.command+(Ext_ID_Tx.operation<<16)+(Ext_ID_Tx.target<<19)+(Ext_ID_Tx.source<<24);
			transmit_message.tx_ft = CAN_FT_DATA;
			transmit_message.tx_ff = CAN_FF_EXTENDED;
			transmit_message.tx_dlen = 6;
			transmit_message.tx_data[0] = MP->speedLimitx100&0xFF;
			transmit_message.tx_data[1] = (MP->speedLimitx100>>8)&0xFF;
			transmit_message.tx_data[2] = (char)'A';
			transmit_message.tx_data[3] = (char)'1';
			transmit_message.tx_data[4] = MP->wheel_cirumference&0xFF;
			transmit_message.tx_data[5] = (MP->wheel_cirumference>>8)&0xFF;

			/* transmit message */
			transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
			/* waiting for transmit completed */
			timeout = 0xFFFF;
			while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
				timeout--;
				}
			break;

		case 0x6200: //to do
			/* initialize transmit message */

			Ext_ID_Tx.command = 0x6200;
			Ext_ID_Tx.operation = NORMAL_ACK; //write
			Ext_ID_Tx.target = Ext_ID_Rx.source; //reply to the requester (display=3, BESST=5...) - was hardcoded 5
			Ext_ID_Tx.source = 0x02; //controller
			transmit_message.tx_sfid = 0x00;
			transmit_message.tx_efid = Ext_ID_Tx.command+(Ext_ID_Tx.operation<<16)+(Ext_ID_Tx.target<<19)+(Ext_ID_Tx.source<<24);
			transmit_message.tx_ft = CAN_FT_DATA;
			transmit_message.tx_ff = CAN_FF_EXTENDED;
			transmit_message.tx_dlen = 0;
			/* transmit message */
			transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
			/* waiting for transmit completed */
			timeout = 0xFFFF;
			while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
				timeout--;
				}
			break;

		case 0x6003: //to do
			/* initialize transmit message */
			if(Ext_ID_Rx.operation==1){
			tx_data_length=sprintf(tx_data, "MMG532.250.CF3YA120681");
			send_multiframe(Ext_ID_Rx.command, &tx_data[0],tx_data_length );
			}
			break;
		case 0x6007: //Error codes read by HMI; report active code (e.g. 10 overtemp). FORMAT TBD - verify vs real HMI
			if(Ext_ID_Rx.operation==1){
				if(MS->error_state) tx_data_length=sprintf(tx_data, "%d", MS->error_state); //active error as ASCII
				else                tx_data_length=sprintf(tx_data, "0");                    //no error
				send_multiframe(Ext_ID_Rx.command, &tx_data[0], tx_data_length);
			}
			break;
		case 0x6010: //reply depends on WHO asks:
			//- HMI display (source=3): factory 4-byte mini config block (0x821B6003 Data:01 00 02 06), NOT Para0.
			//  Sending Para0 (64B multiframe) to the display breaks the HMI info handshake -> Info/Settings blank.
			//- BESST/Canable tool (source=5): full Para0 multiframe - the Full Assist tab reads its data here;
			//  without it the tab stays inactive (nothing downloads).
			if(Ext_ID_Rx.operation==1){
				if(Ext_ID_Rx.source==5){
					send_multiframe(Ext_ID_Rx.command, &Para0[0],64 );
				}else{
					Ext_ID_Tx.command  = 0x6003;              //factory tags this reply as 0x6003, op=3
					Ext_ID_Tx.operation= 3;
					Ext_ID_Tx.target   = Ext_ID_Rx.source;    //reply to requester (display=3)
					Ext_ID_Tx.source   = 0x02;                //controller
					transmit_message.tx_sfid = 0x00;
					transmit_message.tx_efid = Ext_ID_Tx.command+(Ext_ID_Tx.operation<<16)+(Ext_ID_Tx.target<<19)+(Ext_ID_Tx.source<<24);
					transmit_message.tx_ft = CAN_FT_DATA;
					transmit_message.tx_ff = CAN_FF_EXTENDED;
					transmit_message.tx_dlen = 4;
					transmit_message.tx_data[0]=0x01; transmit_message.tx_data[1]=0x00;
					transmit_message.tx_data[2]=0x02; transmit_message.tx_data[3]=0x06;
					transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
					timeout = 0xFFFF;
					while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)) timeout--;
				}
			}
			break;
		case 0x6011: //to do
			/* initialize transmit message */
			if(Ext_ID_Rx.operation==1){
			send_multiframe(Ext_ID_Rx.command, &Para1[0],64 );
			}
			break;
		case 0x6020: //FW-006: read one profile bank (Canable only); rx_data[0] = bank index
			if(Ext_ID_Rx.operation==1 && Ext_ID_Rx.source==5){
				uint8_t bank = (receive_message.rx_dlen>=1) ? receive_message.rx_data[0] : 0;
				if(assist_modes_serialize_bank(bank, &BankBlob[0])){
					send_multiframe(Ext_ID_Rx.command, (char*)&BankBlob[0], ASSIST_BANK_BLOB_LEN);
				}
			}
			break;
		case 0x6023: //FW-010: read global ride-feel tuning (Canable only)
			if(Ext_ID_Rx.operation==1 && Ext_ID_Rx.source==5){
				tuning_config_serialize(&TuningBlob[0]);
				send_multiframe(Ext_ID_Rx.command, (char*)&TuningBlob[0], TUNING_BLOB_LEN);
			}
			break;
		case 0x6025: //FW-013: read torque load telemetry + calibration status (Canable only)
			if(Ext_ID_Rx.operation==1 && Ext_ID_Rx.source==5){
				torque_input_serialize_telemetry(&TorqueBlob[0]);
				send_multiframe(Ext_ID_Rx.command, (char*)&TorqueBlob[0], TORQUE_TELEMETRY_BLOB_LEN);
			}
			break;
		case 0x6029: //FW-015: read TSDZ ride-core diagnostics (peak-hold since last read) (Canable only)
			if(Ext_ID_Rx.operation==1 && Ext_ID_Rx.source==5){
				uint8_t dg[24];
				dg[0]=0x44; dg[1]=0x47; dg[2]=1; //'D''G' ver1
				dg[3]=(uint8_t)ride_control_get_engine();
				uint32_t bcur = diag_peak_motor_w ? ((uint32_t)diag_peak_motor_w*1000000UL)/(MS->Voltage?MS->Voltage:40000) : 0; if(bcur>65535)bcur=65535;
				int32_t iqr = diag_peak_iq_req; if(iqr>32767)iqr=32767; else if(iqr<0)iqr=0;
				dg[4]=diag_peak_cadence; dg[5]=0;
				dg[6]=diag_peak_torque&0xFF; dg[7]=(diag_peak_torque>>8)&0xFF;
				dg[8]=diag_peak_human_w&0xFF; dg[9]=(diag_peak_human_w>>8)&0xFF;
				dg[10]=diag_peak_support&0xFF; dg[11]=(diag_peak_support>>8)&0xFF;
				dg[12]=diag_peak_motor_w&0xFF; dg[13]=(diag_peak_motor_w>>8)&0xFF;
				dg[14]=bcur&0xFF; dg[15]=(bcur>>8)&0xFF;
				dg[16]=iqr&0xFF; dg[17]=(iqr>>8)&0xFF;
				dg[18]=diag_peak_iq_set&0xFF; dg[19]=(diag_peak_iq_set>>8)&0xFF; //peak setpoint reaching FOC
				dg[20]=MS->Speedx100&0xFF; dg[21]=(MS->Speedx100>>8)&0xFF;
				uint16_t c=0xFFFF; for(uint8_t i=0;i<22;i++){c^=(uint16_t)dg[i]<<8; for(uint8_t b=0;b<8;b++)c=(c&0x8000)?((c<<1)^0x1021):(c<<1);}
				dg[22]=c&0xFF; dg[23]=(c>>8)&0xFF;
				send_multiframe(Ext_ID_Rx.command, (char*)&dg[0], 24);
				diag_peak_reset=1; //next 4kHz cycle clears the peaks
			}
			break;
		case 0x6028: //FW-014: read system status (ride engine active/pending) (Canable only)
			if(Ext_ID_Rx.operation==1 && Ext_ID_Rx.source==5){
				uint8_t sys[8]; sys[0]=0x53; sys[1]=0x59; sys[2]=1; //'S''Y' ver1
				sys[3]=(uint8_t)ride_control_get_engine();
				sys[4]=(ride_engine_request==0xFF)?0xFF:ride_engine_request;
				sys[5]=0; sys[6]=0;
				uint16_t c=0xFFFF; for(uint8_t i=0;i<7;i++){c^=(uint16_t)sys[i]<<8; for(uint8_t b=0;b<8;b++)c=(c&0x8000)?((c<<1)^0x1021):(c<<1);}
				sys[7]=(uint8_t)(c&0xFF); //1-byte CRC lo (8-byte frame; single-frame status)
				send_multiframe(Ext_ID_Rx.command, (char*)&sys[0], 8);
			}
			break;
		case 0x6012: //to do
			/* initialize transmit message */
			if(Ext_ID_Rx.operation==1){
			send_multiframe(Ext_ID_Rx.command, &Para2[0],64 );
			//Trailing mini-block AFTER Para2: factory sends 0x821B6012 Data:01 00 02 06 as the
			//"config transfer complete" marker. Without it the HMI never renders the Info/Settings screen.
			Ext_ID_Tx.command = 0x6012; Ext_ID_Tx.operation = 3; Ext_ID_Tx.target = Ext_ID_Rx.source; Ext_ID_Tx.source = 0x02;
			transmit_message.tx_sfid = 0x00;
			transmit_message.tx_efid = Ext_ID_Tx.command+(Ext_ID_Tx.operation<<16)+(Ext_ID_Tx.target<<19)+(Ext_ID_Tx.source<<24);
			transmit_message.tx_ft = CAN_FT_DATA; transmit_message.tx_ff = CAN_FF_EXTENDED; transmit_message.tx_dlen = 4;
			transmit_message.tx_data[0]=0x01; transmit_message.tx_data[1]=0x00; transmit_message.tx_data[2]=0x02; transmit_message.tx_data[3]=0x06;
			transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
			timeout = 0xFFFF; while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)) timeout--;
			}
			break;

	}//end case
}

void send_multiframe(uint16_t command, char* data, uint8_t length ){


			//send multiframe start
			Ext_ID_Tx.command = command;
			Ext_ID_Tx.operation = LONG_START_CMD;
			Ext_ID_Tx.target = Ext_ID_Rx.source; //reply to the requester (display=3, BESST=5...) - was hardcoded 5
			Ext_ID_Tx.source = 0x02; //controller
			transmit_message.tx_sfid = 0x00;
			transmit_message.tx_efid = Ext_ID_Tx.command+(Ext_ID_Tx.operation<<16)+(Ext_ID_Tx.target<<19)+(Ext_ID_Tx.source<<24);
			transmit_message.tx_ft = CAN_FT_DATA;
			transmit_message.tx_ff = CAN_FF_EXTENDED;
			transmit_message.tx_dlen = 1;
			transmit_message.tx_data[0] = length;


			/* transmit message */
			transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
			/* waiting for transmit completed */
			timeout = 0xFFFF;
			while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
				timeout--;
				}

			//send multiframe data
			if(length%8)nbrofframes = (length>>3);
			else nbrofframes = (length>>3)-1;

			for (k=0; k < nbrofframes; k++){
				Ext_ID_Tx.command = k;
				Ext_ID_Tx.operation = LONG_TRANG_CMD;
				Ext_ID_Tx.target = Ext_ID_Rx.source; //reply to the requester (display=3, BESST=5...) - was hardcoded 5
				Ext_ID_Tx.source = 0x02; //controller
				transmit_message.tx_sfid = 0x00;
				transmit_message.tx_efid = Ext_ID_Tx.command+(Ext_ID_Tx.operation<<16)+(Ext_ID_Tx.target<<19)+(Ext_ID_Tx.source<<24);
				transmit_message.tx_ft = CAN_FT_DATA;
				transmit_message.tx_ff = CAN_FF_EXTENDED;
				transmit_message.tx_dlen = 8;
				memcpy(&transmit_message.tx_data, data+k*8,8);


				/* transmit message */
				transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
				timeout = 0xFFFF;
				while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
					timeout--;
					}
			}

			//send multiframe end
			Ext_ID_Tx.command = k;
			Ext_ID_Tx.operation = LONG_END_CMD;
			Ext_ID_Tx.target = Ext_ID_Rx.source; //reply to the requester (display=3, BESST=5...) - was hardcoded 5
			Ext_ID_Tx.source = 0x02; //controller
			transmit_message.tx_sfid = 0x00;
			transmit_message.tx_efid = Ext_ID_Tx.command+(Ext_ID_Tx.operation<<16)+(Ext_ID_Tx.target<<19)+(Ext_ID_Tx.source<<24);
			transmit_message.tx_ft = CAN_FT_DATA;
			transmit_message.tx_ff = CAN_FF_EXTENDED;
			if(length%8){
			transmit_message.tx_dlen = length%8;//rest of data
			memcpy(&transmit_message.tx_data, data+k*8,length%8);
				}
			else{
				transmit_message.tx_dlen = 8;//rest of data
				memcpy(&transmit_message.tx_data, data+k*8,8);
					}
			/* transmit message */
			transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
			/* waiting for transmit completed */
			timeout = 0xFFFF;
			while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
				timeout--;
				}

}

void append_multiframe(uint16_t command, char* data){
	memcpy(data+command*8, &receive_message.rx_data,receive_message.rx_dlen );

}

void update_checksum(void){
	checksum=0;
	for (k=0; k < 63; k++){
		//Para0[k]=k;
		checksum+=Para0[k];
	}
	Para0[63]=checksum%256;
	checksum=0;
	for (k=0; k < 63; k++){
		//Para1[k]=k+64;
		checksum+=Para1[k];
	}
	Para1[63]=checksum%256;
	checksum=0;
	for (k=0; k < 63; k++){
		//Para2[k]=k+128;
		checksum+=Para2[k];
	}
	Para2[63]=checksum%256;
	checksum=0;
}

//int16_t abs(int16_t value){
//
//	if(value>0)return value;
//	else return -value;
//
//}
