/*
 * CAN_Display.c
 *
 *  Created on: 19.10.2025
 *  Author: stancecoke
	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


#include "main.h"
#include "CAN_Display.h"
#include "parser.h"
#include "FOC.h"

/* Build version string for the HMI info field (0x6001). Generated by build_firmware.ps1
   into inc/build_version.h (gitignored, never committed). Falls back to "dev" for IDE builds. */
#if defined(__has_include)
#  if __has_include("build_version.h")
#    include "build_version.h"
#  endif
#endif
#ifndef EBICS_BUILD_VERSION
#define EBICS_BUILD_VERSION "dev"
#endif

Ext_ID_t Ext_ID_Rx;
Ext_ID_t Ext_ID_Tx;
void processCAN_Rx(MotorParams_t* MP, MotorState_t* MS);
void sendCAN_Tx(MotorParams_t* MP, MotorState_t* MS);
void sendCAN_Poll(MotorParams_t* MP, MotorState_t* MS, uint16_t command);
void sendAcknoledge(void);
void send_multiframe(uint16_t command, char* data, uint8_t length );
void append_multiframe(uint16_t command, char* data);
void update_checksum(void);
//int16_t abs(int16_t value);
char tx_data[64];
uint8_t Para0[64];
uint8_t Para1[64];
uint8_t Para2[64];
uint8_t tx_data_length;
uint8_t rx_data_length;
uint8_t nbrofframes;
float last_distance =0;
float last_kilometer =0;
float distance =0;
uint16_t display_distance=0;
uint16_t delay_counter =0;
uint16_t k=0;
uint8_t level_code;
uint8_t level_code_old;
uint8_t level_counter;
uint8_t walk_can_code_old;
uint8_t walk_can_counter;

uint16_t Rx_MF_active=0;
uint16_t checksum=0;

void processCAN_Rx(MotorParams_t* MP, MotorState_t* MS){

	Ext_ID_Rx.command = (receive_message.rx_efid)&0xFFFF;
	Ext_ID_Rx.operation = (receive_message.rx_efid>>16)&0x07; //only 3 bit width
	Ext_ID_Rx.target = (receive_message.rx_efid>>19)&0x1F; //only 5 bit width
	Ext_ID_Rx.source = (receive_message.rx_efid>>24)&0x1F;

	//HMI queries controller info on BOTH target=2 (0x8311xxxx) and target=4 (0x8321xxxx). Factory answers both.
	if(Ext_ID_Rx.target==2 || Ext_ID_Rx.target==4){
		switch (Ext_ID_Rx.operation){
			case WRITE_CMD:

				if (receive_message.rx_dlen==1 && receive_message.rx_data[0]>8 && Ext_ID_Rx.source==5){
					Rx_MF_active=Ext_ID_Rx.command;
					rx_data_length=receive_message.rx_data[0];
				}
				else if(Ext_ID_Rx.command==0x62D9){ //Startup angle, used as multiplyer here
					MP->TS_coeff=receive_message.rx_data[0]+(receive_message.rx_data[1]<<8);
					//save received setting
					write_virtual_eeprom();
				}

				else sendCAN_Tx(MP,MS);
				sendAcknoledge();
				break;
			case READ_CMD:
				sendCAN_Tx(MP,MS);
				break;
			case LONG_START_CMD:
				switch (Rx_MF_active){
					case 0x6010: //Para0
						append_multiframe(0, &Para0[0]);
						break;
					case 0x6011: //Para1
						append_multiframe(0, &Para1[0]);
						break;
					case 0x6012: //Para2
						append_multiframe(0, &Para2[0]);
						break;
				}

				break;
			case LONG_TRANG_CMD:
				switch (Rx_MF_active){
					case 0x6010: //Para0
						append_multiframe(Ext_ID_Rx.command+1, &Para0[0]);
						break;
					case 0x6011: //Para1
						append_multiframe(Ext_ID_Rx.command+1, &Para1[0]);
						break;
					case 0x6012: //Para2
						append_multiframe(Ext_ID_Rx.command+1, &Para2[0]);
						break;
				}
				break;

			case LONG_END_CMD:
				switch (Rx_MF_active){
					case 0x6010: //Para0
						append_multiframe(Ext_ID_Rx.command+1, &Para0[0]);
						break;
					case 0x6011: //Para1
						append_multiframe(Ext_ID_Rx.command+1, &Para1[0]);

						break;
					case 0x6012: //Para2
						append_multiframe(Ext_ID_Rx.command+1, &Para2[0]);

						break;
				}
				k = ((Ext_ID_Rx.command+1)<<3)+receive_message.rx_dlen;
				if(((Ext_ID_Rx.command+1)<<3)+receive_message.rx_dlen==rx_data_length){
					//to do send acknoledge OK
					Rx_MF_active=0;
					rx_data_length=0;
					//save received setting
					parse_DPparams(MP);
					write_virtual_eeprom();

				}
				else{
					//to do send acknoledge NOK
					Rx_MF_active=0;
					rx_data_length=0;
				}

				break;
		}


		if(Ext_ID_Rx.command==0x6300){
			level_code=receive_message.rx_data[1];
			if(level_code==level_code_old&&level_counter<3)level_counter++;
			if(level_code!=level_code_old){

				level_counter=0;
				}
			level_code_old=level_code;

			if(level_counter==3){

				level_counter=4;
				switch (level_code){
					case 0:
						MS->assist_level=0;
						break;
					case 1:
						MS->assist_level=1;
						break;
					case 0x0B:
						MS->assist_level=2; //Eco
						break;
					case 0x0C:
						MS->assist_level=3;
						break;
					case 0x0D:
						MS->assist_level=4; //Tour
						break;
					case 0x02:
						MS->assist_level=5;
						break;
					case 0x15:
						MS->assist_level=6;//Sport
						break;
					case 0x16:
						MS->assist_level=7;
						break;
					case 0x17:
						MS->assist_level=8; //Sport +
						break;
					case 0x03:
						MS->assist_level=9; //Boost
						break;
				}
			}
			// Walk Assist request from display: only sets walk_can_request (with debounce).
			// pushassist_flag itself is derived in main.c (requires physical PA4 button held).
			if (receive_message.rx_data[1]==6){
				if(receive_message.rx_data[1]==walk_can_code_old){
					if(walk_can_counter<3)walk_can_counter++;
				}else{
					walk_can_counter=0;
				}
				if(walk_can_counter>=3)MS->walk_can_request=SET;
			}else{
				walk_can_counter=0;
				MS->walk_can_request=RESET;
			}
			walk_can_code_old=receive_message.rx_data[1];
			if (receive_message.rx_data[2]&0b1)MS->light_flag=SET;
			else MS->light_flag=RESET;
			if (receive_message.rx_data[2]&0b10)MS->button_up_flag=SET;
			else MS->button_up_flag=RESET;
			if (receive_message.rx_data[2]&0b100000)MS->button_down_flag=SET;
			else MS->button_down_flag=RESET;

		}

		if(Ext_ID_Rx.command==0x3203&&Ext_ID_Rx.operation==WRITE_CMD){ //speed limit and wheel size
			MP->speedLimitx100=receive_message.rx_data[0]+(receive_message.rx_data[1]<<8);
			MP->wheel_cirumference=receive_message.rx_data[4]+(receive_message.rx_data[5]<<8);
			//save received setting
			write_virtual_eeprom();

		}

		if(Ext_ID_Rx.command==0x6200){ //Position sensor calibration
			autodetect();
		}
		if(Ext_ID_Rx.command==0x6101){ //Torque sensor calibration normally, here used for factory settings reset
			InitEEPROM(MP);
			read_virtual_eeprom();
			parse_MOparams(MP);

		}



	}
	if(Ext_ID_Rx.command==0x3005){ //jump to bootloader for firmware update
		NVIC_SystemReset();
	}
}
void sendAcknoledge(void){
	Ext_ID_Tx.command = Ext_ID_Rx.command;
	Ext_ID_Tx.operation = 2; //acknoledge OK
	Ext_ID_Tx.target = Ext_ID_Rx.source; //reply to the requester - was hardcoded 5
	Ext_ID_Tx.source = 0x02; //controller
	transmit_message.tx_sfid = 0x00;
	transmit_message.tx_efid = Ext_ID_Tx.command+(Ext_ID_Tx.operation<<16)+(Ext_ID_Tx.target<<19)+(Ext_ID_Tx.source<<24);
	transmit_message.tx_ft = CAN_FT_DATA;
	transmit_message.tx_ff = CAN_FF_EXTENDED;
	transmit_message.tx_dlen = 0;

	/* transmit message */
	transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
	/* waiting for transmit completed */
	timeout = 0xFFFF;
	while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
		timeout--;
		}

}

void sendCAN_3100(MotorState_t* MS){
	//Emulates the separate torque-sensor CAN node (source=01) that the original Bafang system has.
	//HMI reads real-time cadence and torque from this frame every 10ms.
	static uint8_t ctr = 0;
	transmit_message.tx_sfid    = 0x00;
	transmit_message.tx_efid    = 0x01F83100; //source=1 (torque sensor), target=31 broadcast
	transmit_message.tx_ft      = CAN_FT_DATA;
	transmit_message.tx_ff      = CAN_FF_EXTENDED;
	transmit_message.tx_dlen    = 4;
	transmit_message.tx_data[0] = (uint8_t)((uint16_t)MS->torque_on_crank & 0xFF);
	transmit_message.tx_data[1] = (uint8_t)((uint16_t)MS->torque_on_crank >> 8);
	transmit_message.tx_data[2] = MS->cadence;
	transmit_message.tx_data[3] = ctr++;
	transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
	timeout = 0xFFFF;
	while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
		timeout--;
	}
}

void sendCAN_3202(void){
	//Original firmware sends 0x3202 (1 byte 0x00) every ~100ms. HMI may lose sync or exit WA without it.
	uint32_t timeout;
	transmit_message.tx_sfid    = 0x00;
	transmit_message.tx_efid    = 0x02F83202;
	transmit_message.tx_ft      = CAN_FT_DATA;
	transmit_message.tx_ff      = CAN_FF_EXTENDED;
	transmit_message.tx_dlen    = 1;
	transmit_message.tx_data[0] = 0x00;
	transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
	timeout = 0xFFFF;
	while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
		timeout--;
	}
}

void sendCAN_Poll(MotorParams_t* MP, MotorState_t* MS, uint16_t command){

	switch (command){

		case 0x3201: //speed and power
			/* initialize transmit message */
			transmit_message.tx_sfid = 0x00;
			transmit_message.tx_efid = 0x02F83201;
			transmit_message.tx_ft = CAN_FT_DATA;
			transmit_message.tx_ff = CAN_FF_EXTENDED;
			transmit_message.tx_dlen = 8;
			if(MS->offroadtics){
				transmit_message.tx_data[0] = (MS->offroadtics*100)&0xFF;
				transmit_message.tx_data[1] = ((MS->offroadtics*100)>>8)&0xFF;
			}
			else{
				transmit_message.tx_data[0] = (MS->Speedx100)&0xFF;
				transmit_message.tx_data[1] = ((MS->Speedx100)>>8)&0xFF;
			}
			transmit_message.tx_data[2] = (abs(MS->Battery_Current)/10)&0xFF;
			transmit_message.tx_data[3] = ((abs(MS->Battery_Current)/10)>>8)&0xFF;
			transmit_message.tx_data[4] = (MS->Voltage/10)&0xFF;
			transmit_message.tx_data[5] = ((MS->Voltage/10)>>8)&0xFF;
			transmit_message.tx_data[6] = MS->int_Temperature+40; //temp sterownika (M820: jeden czujnik); +40 = offset protokolu, parser PC odejmuje 40
			transmit_message.tx_data[7] = MS->int_Temperature+40; //ta sama temp sterownika jako "motor temp"; +40 = offset protokolu (NIE przeklamanie)

			/* transmit message */
			transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
			/* waiting for transmit completed */
			timeout = 0xFFFF;
			while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
				timeout--;
				}
			break;

		case 0x3200: //battery and distance
			/* initialize transmit message */
			if(delay_counter<10)delay_counter++;
			else{
				delay_counter=0;
				distance=(MS->distance_since_startup)-last_kilometer;
				if(MS->distance_since_startup!=last_distance)display_distance = distance/10;
				else{
					display_distance = 0;
					last_kilometer=MS->distance_since_startup;
				}
				if(distance>1000)last_kilometer=MS->distance_since_startup;
				last_distance=MS->distance_since_startup;
			}
			transmit_message.tx_sfid = 0x00;
			transmit_message.tx_efid = 0x02F83200;
			transmit_message.tx_ft = CAN_FT_DATA;
			transmit_message.tx_ff = CAN_FF_EXTENDED;
			transmit_message.tx_dlen = 8;
			transmit_message.tx_data[0] = MS->SOC;//battery percentage
			transmit_message.tx_data[1] = (uint8_t)display_distance; // in 10m
			transmit_message.tx_data[2] = 0x00;
			transmit_message.tx_data[3] = MS->cadence; //cadence
			transmit_message.tx_data[4] = MS->torque_on_crank&0xFF; //torque mV LSB
			transmit_message.tx_data[5] = (MS->torque_on_crank>>8)&0xFF; //torque mv MSB
			//protocol unit for remaining range is 0.01 km (display divides by 100) -> send km*100
			{
				uint16_t range_x100 = (MS->range < 650) ? (uint16_t)(MS->range*100) : 64999;
				transmit_message.tx_data[6] = range_x100&0xFF;//range LSB (0.01 km)
				transmit_message.tx_data[7] = (range_x100>>8)&0xFF;//range MSB
			}

			/* transmit message */
			transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
			/* waiting for transmit completed */
			timeout = 0xFFFF;
			while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
				timeout--;
				}

			break;

		case 0x3205: //to do
			/* initialize transmit message */
			transmit_message.tx_sfid = 0x00;
			transmit_message.tx_efid = 0x02F83205;
			transmit_message.tx_ft = CAN_FT_DATA;
			transmit_message.tx_ff = CAN_FF_EXTENDED;
			transmit_message.tx_dlen = 2;
			transmit_message.tx_data[0] = MS->calories&0xFF; //calories
			transmit_message.tx_data[1] = (MS->calories>>8)&0xFF;


			/* transmit message */
			transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
			/* waiting for transmit completed */
			timeout = 0xFFFF;
			while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
				timeout--;
				}
			break;


	}//end case
}

void sendCAN_status_broadcast(MotorState_t* MS){
	//Controller alive/status heartbeat broadcast to HMI (replicates factory M820 firmware).
	//Without these the HMI does not blink the Walk Assist icon and drops out of WA after a few seconds.
	//Frames (source=2 controller, target=31 broadcast): 0x1200 (warning/brake), 0x320F (status active), 0x3000.
	static const uint32_t hb_efid[3] = {0x02FF1200, 0x02F8320F, 0x02F83000};
	static const uint8_t  hb_dlen[3] = {1, 8, 4};
	for(uint8_t i=0;i<3;i++){
		transmit_message.tx_sfid = 0x00;
		transmit_message.tx_efid = hb_efid[i];
		transmit_message.tx_ft = CAN_FT_DATA;
		transmit_message.tx_ff = CAN_FF_EXTENDED;
		transmit_message.tx_dlen = hb_dlen[i];
		for(uint8_t j=0;j<8;j++) transmit_message.tx_data[j]=0;
		if(i==0) transmit_message.tx_data[0] = (MS->brake_active_flag==SET) ? 0x01 : 0x00; //bit0=brake
		else if(i==1) transmit_message.tx_data[0] = 0x01;
		else { transmit_message.tx_data[3] = 0x0B; } //0x3000: byte3=0x0B matches orig firmware
		transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
		timeout = 0xFFFF;
		while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
			timeout--;
		}
	}
}

void sendCAN_Tx(MotorParams_t* MP, MotorState_t* MS){

	switch (Ext_ID_Rx.command){


		// Controller info as MULTIFRAME (like factory firmware) so the HMI shows name/version.
		// Strings kept factory-identical except the customer/serial field (0x6001) -> EBICS + build version.
		case 0x6000: //manufacturer / hw id (factory: "CR X30P.250.FC 2.1")
			if(Ext_ID_Rx.operation==1){
				tx_data_length=sprintf(tx_data, "CR X30P.250.FC 2.1");
				send_multiframe(Ext_ID_Rx.command, &tx_data[0], tx_data_length);
			}
			break;

		case 0x6001: //serial/customer field -> EBICS + current build version (factory was "FAKE TAXI ...")
			if(Ext_ID_Rx.operation==1){
				tx_data_length=sprintf(tx_data, "EBICS %s", EBICS_BUILD_VERSION);
				while(tx_data_length<20) tx_data[tx_data_length++]=' '; //pad to factory serial length (20)
				send_multiframe(Ext_ID_Rx.command, &tx_data[0], tx_data_length);
			}
			break;

		case 0x6002: //model number shown on HMI (factory: "CR X30P.250.FC")
			if(Ext_ID_Rx.operation==1){
				tx_data_length=sprintf(tx_data, "CR X30P.250.FC");
				send_multiframe(Ext_ID_Rx.command, &tx_data[0], tx_data_length);
			}
			break;

		case 0x62D9: //startup angle used as multiplyer here
			/* initialize transmit message */

			Ext_ID_Tx.command = 0x62D9;
			Ext_ID_Tx.operation = 0; //write
			Ext_ID_Tx.target = Ext_ID_Rx.source; //reply to the requester (display=3, BESST=5...) - was hardcoded 5
			Ext_ID_Tx.source = 0x02; //controller
			transmit_message.tx_sfid = 0x00;
			transmit_message.tx_efid = Ext_ID_Tx.command+(Ext_ID_Tx.operation<<16)+(Ext_ID_Tx.target<<19)+(Ext_ID_Tx.source<<24);
			transmit_message.tx_ft = CAN_FT_DATA;
			transmit_message.tx_ff = CAN_FF_EXTENDED;
			transmit_message.tx_dlen = 2;
			transmit_message.tx_data[0] =  (MP->TS_coeff)&0xFF;
			transmit_message.tx_data[1] =  (MP->TS_coeff>>8)&0xFF;

			/* transmit message */
			transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
			/* waiting for transmit completed */
			timeout = 0xFFFF;
			while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
				timeout--;
				}
			break;

		case 0x3203: //to do
			/* initialize transmit message */

			Ext_ID_Tx.command = 0x3203;
			Ext_ID_Tx.operation = 0; //write
			Ext_ID_Tx.target = Ext_ID_Rx.source; //reply to the requester (display=3, BESST=5...) - was hardcoded 5
			Ext_ID_Tx.source = 0x02; //controller
			transmit_message.tx_sfid = 0x00;
			transmit_message.tx_efid = Ext_ID_Tx.command+(Ext_ID_Tx.operation<<16)+(Ext_ID_Tx.target<<19)+(Ext_ID_Tx.source<<24);
			transmit_message.tx_ft = CAN_FT_DATA;
			transmit_message.tx_ff = CAN_FF_EXTENDED;
			transmit_message.tx_dlen = 6;
			transmit_message.tx_data[0] = MP->speedLimitx100&0xFF;
			transmit_message.tx_data[1] = (MP->speedLimitx100>>8)&0xFF;
			transmit_message.tx_data[2] = (char)'A';
			transmit_message.tx_data[3] = (char)'1';
			transmit_message.tx_data[4] = MP->wheel_cirumference&0xFF;
			transmit_message.tx_data[5] = (MP->wheel_cirumference>>8)&0xFF;

			/* transmit message */
			transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
			/* waiting for transmit completed */
			timeout = 0xFFFF;
			while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
				timeout--;
				}
			break;

		case 0x6200: //to do
			/* initialize transmit message */

			Ext_ID_Tx.command = 0x6200;
			Ext_ID_Tx.operation = NORMAL_ACK; //write
			Ext_ID_Tx.target = Ext_ID_Rx.source; //reply to the requester (display=3, BESST=5...) - was hardcoded 5
			Ext_ID_Tx.source = 0x02; //controller
			transmit_message.tx_sfid = 0x00;
			transmit_message.tx_efid = Ext_ID_Tx.command+(Ext_ID_Tx.operation<<16)+(Ext_ID_Tx.target<<19)+(Ext_ID_Tx.source<<24);
			transmit_message.tx_ft = CAN_FT_DATA;
			transmit_message.tx_ff = CAN_FF_EXTENDED;
			transmit_message.tx_dlen = 0;
			/* transmit message */
			transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
			/* waiting for transmit completed */
			timeout = 0xFFFF;
			while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
				timeout--;
				}
			break;

		case 0x6003: //to do
			/* initialize transmit message */
			if(Ext_ID_Rx.operation==1){
			tx_data_length=sprintf(tx_data, "MMG532.250.CF3YA120681");
			send_multiframe(Ext_ID_Rx.command, &tx_data[0],tx_data_length );
			}
			break;
		case 0x6007: //Error codes read by HMI; report active code (e.g. 10 overtemp). FORMAT TBD - verify vs real HMI
			if(Ext_ID_Rx.operation==1){
				if(MS->error_state) tx_data_length=sprintf(tx_data, "%d", MS->error_state); //active error as ASCII
				else                tx_data_length=sprintf(tx_data, "0");                    //no error
				send_multiframe(Ext_ID_Rx.command, &tx_data[0], tx_data_length);
			}
			break;
		case 0x6010: //factory replies with a 4-byte mini config block (0x821B6003 Data:01 00 02 06), NOT Para0.
			//Sending Para0 (64B multiframe) here breaks the HMI info handshake -> whole Info/Settings screen stays blank.
			if(Ext_ID_Rx.operation==1){
				Ext_ID_Tx.command  = 0x6003;              //factory tags this reply as 0x6003, op=3
				Ext_ID_Tx.operation= 3;
				Ext_ID_Tx.target   = Ext_ID_Rx.source;    //reply to requester (display=3)
				Ext_ID_Tx.source   = 0x02;                //controller
				transmit_message.tx_sfid = 0x00;
				transmit_message.tx_efid = Ext_ID_Tx.command+(Ext_ID_Tx.operation<<16)+(Ext_ID_Tx.target<<19)+(Ext_ID_Tx.source<<24);
				transmit_message.tx_ft = CAN_FT_DATA;
				transmit_message.tx_ff = CAN_FF_EXTENDED;
				transmit_message.tx_dlen = 4;
				transmit_message.tx_data[0]=0x01; transmit_message.tx_data[1]=0x00;
				transmit_message.tx_data[2]=0x02; transmit_message.tx_data[3]=0x06;
				transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
				timeout = 0xFFFF;
				while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)) timeout--;
			}
			break;
		case 0x6011: //to do
			/* initialize transmit message */
			if(Ext_ID_Rx.operation==1){
			send_multiframe(Ext_ID_Rx.command, &Para1[0],64 );
			}
			break;
		case 0x6012: //to do
			/* initialize transmit message */
			if(Ext_ID_Rx.operation==1){
			send_multiframe(Ext_ID_Rx.command, &Para2[0],64 );
			}
			break;

	}//end case
}

void send_multiframe(uint16_t command, char* data, uint8_t length ){


			//send multiframe start
			Ext_ID_Tx.command = command;
			Ext_ID_Tx.operation = LONG_START_CMD;
			Ext_ID_Tx.target = Ext_ID_Rx.source; //reply to the requester (display=3, BESST=5...) - was hardcoded 5
			Ext_ID_Tx.source = 0x02; //controller
			transmit_message.tx_sfid = 0x00;
			transmit_message.tx_efid = Ext_ID_Tx.command+(Ext_ID_Tx.operation<<16)+(Ext_ID_Tx.target<<19)+(Ext_ID_Tx.source<<24);
			transmit_message.tx_ft = CAN_FT_DATA;
			transmit_message.tx_ff = CAN_FF_EXTENDED;
			transmit_message.tx_dlen = 1;
			transmit_message.tx_data[0] = length;


			/* transmit message */
			transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
			/* waiting for transmit completed */
			timeout = 0xFFFF;
			while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
				timeout--;
				}

			//send multiframe data
			if(length%8)nbrofframes = (length>>3);
			else nbrofframes = (length>>3)-1;

			for (k=0; k < nbrofframes; k++){
				Ext_ID_Tx.command = k;
				Ext_ID_Tx.operation = LONG_TRANG_CMD;
				Ext_ID_Tx.target = Ext_ID_Rx.source; //reply to the requester (display=3, BESST=5...) - was hardcoded 5
				Ext_ID_Tx.source = 0x02; //controller
				transmit_message.tx_sfid = 0x00;
				transmit_message.tx_efid = Ext_ID_Tx.command+(Ext_ID_Tx.operation<<16)+(Ext_ID_Tx.target<<19)+(Ext_ID_Tx.source<<24);
				transmit_message.tx_ft = CAN_FT_DATA;
				transmit_message.tx_ff = CAN_FF_EXTENDED;
				transmit_message.tx_dlen = 8;
				memcpy(&transmit_message.tx_data, data+k*8,8);


				/* transmit message */
				transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
				timeout = 0xFFFF;
				while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
					timeout--;
					}
			}

			//send multiframe end
			Ext_ID_Tx.command = k;
			Ext_ID_Tx.operation = LONG_END_CMD;
			Ext_ID_Tx.target = Ext_ID_Rx.source; //reply to the requester (display=3, BESST=5...) - was hardcoded 5
			Ext_ID_Tx.source = 0x02; //controller
			transmit_message.tx_sfid = 0x00;
			transmit_message.tx_efid = Ext_ID_Tx.command+(Ext_ID_Tx.operation<<16)+(Ext_ID_Tx.target<<19)+(Ext_ID_Tx.source<<24);
			transmit_message.tx_ft = CAN_FT_DATA;
			transmit_message.tx_ff = CAN_FF_EXTENDED;
			if(length%8){
			transmit_message.tx_dlen = length%8;//rest of data
			memcpy(&transmit_message.tx_data, data+k*8,length%8);
				}
			else{
				transmit_message.tx_dlen = 8;//rest of data
				memcpy(&transmit_message.tx_data, data+k*8,8);
					}
			/* transmit message */
			transmit_mailbox = can_message_transmit(CAN0, &transmit_message);
			/* waiting for transmit completed */
			timeout = 0xFFFF;
			while((CAN_TRANSMIT_OK != can_transmit_states(CAN0, transmit_mailbox)) && (0 != timeout)){
				timeout--;
				}

}

void append_multiframe(uint16_t command, char* data){
	memcpy(data+command*8, &receive_message.rx_data,receive_message.rx_dlen );

}

void update_checksum(void){
	checksum=0;
	for (k=0; k < 63; k++){
		//Para0[k]=k;
		checksum+=Para0[k];
	}
	Para0[63]=checksum%256;
	checksum=0;
	for (k=0; k < 63; k++){
		//Para1[k]=k+64;
		checksum+=Para1[k];
	}
	Para1[63]=checksum%256;
	checksum=0;
	for (k=0; k < 63; k++){
		//Para2[k]=k+128;
		checksum+=Para2[k];
	}
	Para2[63]=checksum%256;
	checksum=0;
}

//int16_t abs(int16_t value){
//
//	if(value>0)return value;
//	else return -value;
//
//}
